# Generated by Django 4.0 on 2025-04-18 00:21

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dash', '0004_alter_payment_amount'),
        ('registration', '0002_alter_myuser_date_joined_alter_myuser_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('task_img', models.ImageField(upload_to='taskimage')),
                ('links', models.URLField()),
                ('task_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task_collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('complete', 'complete')], max_length=200)),
                ('screen_short', models.ImageField(upload_to='taskimage')),
                ('links', models.URLField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_created=True, blank=True, null=True)),
                ('ending_date', models.DateField(auto_created=True, blank=True, null=True)),
                ('project_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('expired', 'expired'), ('active', 'active'), ('pending', 'pending')], default='pending', max_length=200)),
                ('descriptions', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('cohorts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dash.cohorts')),
            ],
        ),
        migrations.CreateModel(
            name='Assigment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_hub', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=10000)),
                ('date', models.DateField(auto_now_add=True)),
                ('passcode', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('reviewing', 'reviewing'), ('complete', 'complete'), ('reject', 'reject')], default='reviewing', max_length=200)),
                ('score_project', models.IntegerField(default=1)),
                ('cohorts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.cohorts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.myuser')),
            ],
        ),
    ]
