# Generated by Django 5.2 on 2025-05-07 08:04

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnqszxcvopl1234567890*&^%$#@', editable=False, length=22, max_length=22, prefix='', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='task_collections',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnqszxcvopl1234567890*&^%$#@', editable=False, length=22, max_length=22, prefix='', primary_key=True, serialize=False, unique=True),
        ),
    ]
