# Generated by Django 5.2 on 2025-05-22 06:11

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnqszxcvopl1234567890', editable=False, length=22, max_length=22, prefix='', primary_key=True, serialize=False, unique=True)),
                ('topic', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='live_class_images/')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('join_link', models.URLField()),
                ('attendance_points', models.PositiveIntegerField(default=0)),
                ('enable_attendance', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('finished', 'Finished')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='courses.course')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiveClassAttendance',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnqszxcvopl1234567890', editable=False, length=22, max_length=22, prefix='', primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='liveclass.liveclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('live_class', 'student')},
            },
        ),
    ]
