# Generated by Django 5.2 on 2025-05-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newdash', '0003_alter_facilitatorregistration_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='FacilitatorRegistration',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
