# Generated by Django 5.2 on 2025-05-22 07:29

import ckeditor_uploader.fields
import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnqszxcvopl1234567890', editable=False, length=22, max_length=22, prefix='', primary_key=True, serialize=False, unique=True)),
                ('task', models.CharField(max_length=200)),
                ('task_img', models.ImageField(upload_to='taskimage')),
                ('links', models.URLField()),
                ('task_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task_collections',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnqszxcvopl1234567890', editable=False, length=22, max_length=22, prefix='', primary_key=True, serialize=False, unique=True)),
                ('task', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('complete', 'complete')], max_length=200)),
                ('screen_short', models.ImageField(upload_to='taskimage')),
                ('links', models.URLField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
