# Generated by Django 5.2 on 2025-05-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_myuser_date_joined_alter_myuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_facilitator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_verified_facilitator',
            field=models.BooleanField(default=False),
        ),
    ]
