# Generated by Django 5.2 on 2025-05-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='manual_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='manually_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('installment', 'Installment (50%)'), ('full', 'Full Payment (100%)'), ('none', 'No Payment Required')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('flutterwave', 'Flutterwave'), ('manual', 'Manual Approval')], max_length=20),
        ),
    ]
