# Generated by Django 5.2 on 2025-05-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_id_alter_courseregistration_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('flutterwave', 'Flutterwave')], max_length=20),
        ),
    ]
