# Generated by Django 5.2 on 2025-05-10 07:51

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_paymentdetail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnqszxcvopl1234567890*&^%$#@', editable=False, length=22, max_length=22, prefix='', primary_key=True, serialize=False, unique=True),
        ),
    ]
