# Generated by Django 4.0 on 2025-04-18 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0002_alter_myuser_date_joined_alter_myuser_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('local_govt', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=200)),
                ('contact_add', models.CharField(max_length=600)),
                ('laptop', models.CharField(max_length=200)),
                ('certifcate', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('admitted', 'admitted')], default='pending', max_length=50)),
                ('uplaod_picture', models.ImageField(default=2, upload_to='profile')),
                ('sponsorship', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.myuser')),
            ],
        ),
    ]
