# Generated by Django 5.2 on 2025-05-22 06:11

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnqszxcvopl1234567890', editable=False, length=22, max_length=22, prefix='', primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('local_govt', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=200)),
                ('contact_add', models.CharField(max_length=600)),
                ('laptop', models.CharField(max_length=200)),
                ('certifcate', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('admitted', 'admitted')], default='pending', max_length=50)),
                ('uplaod_picture', models.ImageField(default=2, upload_to='profile')),
                ('sponsorship', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
