# Generated by Django 5.2 on 2025-05-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_profiles_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
