# Generated by Django 4.0 on 2025-04-15 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('courses', models.CharField(max_length=200)),
                ('payment_type', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('uplaod', models.ImageField(upload_to='payment')),
                ('passcode', models.CharField(max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('reject', 'reject')], default='pending', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Mypasscode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcodeNo', models.CharField(max_length=200, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Cohorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('whatsapp', models.CharField(blank=True, default='hello', max_length=400, null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
