# Generated by Django 4.0 on 2025-04-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_cohorts_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
