# Generated by Django 4.0 on 2025-04-15 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ourteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('files', models.FileField(upload_to='ourteam')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Recapcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trainingsession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recapsesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=300)),
                ('image', models.ImageField(upload_to='sesion')),
                ('courses', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cohorts.recapcourse')),
            ],
        ),
        migrations.CreateModel(
            name='Livesesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(max_length=300)),
                ('image', models.ImageField(upload_to='sesion')),
                ('online', models.CharField(choices=[('coming soon', 'coming soon'), ('live', 'live')], default='coming soon', max_length=300)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohorts.trainingsession')),
            ],
        ),
    ]
