# Generated by Django 5.2 on 2025-05-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlyscore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemonthlyrequirement',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursemonthlyrequirement',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
